model: ADLChargeDriftModel
phi110: 0
material: Si
drift:
  velocity:
    model: Bruyneel2006
    temperature: 300
    parameters:
      e100:
        mu0: 0.144
        beta: 0.992
        E0: 731944
        mun: 0
      e111:
        mu0: 0.144
        beta: 1.075
        E0: 731944
        mun: 0
      h100:
        mu0: 0.0474
        beta: 1.181
        E0: 1983122
      h111:
        mu0: 0.0474
        beta: 0.924
        E0: 1983122