name: ExampleCuboid
units:
  length: mm
  angle: deg
  potential: V
  temperature: K
grid:
  coordinates: cartesian
  axes:
    x:
      from: -15
      to: 15
      boundaries: inf
    y:
      from: -15
      to: 15
      boundaries: inf
    z:
      from: -15
      to: 15
      boundaries: inf
medium: vacuum
detectors:
  - translate: 
      x: 0
    rotate: 
      Z: 45
    bulk:
      material: HPGe
      temperature: 78
      impurity_density:
        name: linear
        x:
          init: 0
          gradient: 0
        y:
          init: 0
          gradient: 0
        z:
          init: 10000000
          gradient: 50000
      charge_drift_model:
        include: ADLChargeDriftModel/drift_velocity_config.json
      geometry:
        box:
          x: 10 # width in x
          y: 10 # width in y
          z: 10 # width in z
    contacts:
      - material: HPGe
        name: n+ contact
        potential: 2000
        channel: 1
        geometry:
          box:
            x: 
              from: -5
              to: -4.9
            y: 10
            z: 10
      - material: HPGe
        name: p+ contact
        potential: 0
        channel: 2
        geometry:
          box:
            x: 
              from: 4.9
              to: 5
            y: 10
            z: 10

surroundings:
  - name: Base
    material: Copper
    potential: 0
    geometry:
      box:
        x:
          from: -15
          to: 15
        y:
          from: -15
          to: 15
        z:
          from: -7
          to: -6
